application:
  name: sendMailAPI
  project: send-mail-api
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: sendMailAPI
    paths:
    - /
